default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_38933_development

test:
  <<: *default
  database: furima_38933_test

production:
  <<: *default
  database: furima_38933_production
  username: furima_38933
  password: <%= ENV['FURIMA_38933_DATABASE_PASSWORD'] %>
